### ISSUE TITLE
File header in .map files

### ISSUE THREAD

**Issue by Duefectu** [remy/zx-tools#14]
The download map option creates a file with a 128 bytes header.
![image](https://user-images.githubusercontent.com/5257547/82116737-2cacb680-976c-11ea-9c42-7354d13aa048.png)
I load this file with LoadSD from NextLib.bas, and the 128 bytes goes to memory.

In .spr files there aren't this header.

Keep the good work!

**Comment by remy** [comment]
Okay, so you're using the [zxbasic](https://zxbasic.readthedocs.io/en/latest/) compiler to ASM which I'm guessing (though I've no experience) doesn't need the plus3dos header - because in NextBASIC I expected the file to be loaded with `LOAD "my-map.map" BANK …`.

I suspect the option to set the header would solve this to allow for both usages.

I'll add something today to work around this as I suspect it's a bit of a blocker.

**Comment by remy** [comment]
Live - thanks for the request.

<img width="351" alt="Screenshot 2020-05-16 at 18 37 36" src="https://user-images.githubusercontent.com/13700/82126400-6c8f9000-97a4-11ea-8607-e789e91889cd.png">

I'm defaulting for NextBASIC the header is included by default, but now you can opt out of the header and it should work for your code.

**Comment by Duefectu** [comment]
Great!
