### ISSUE TITLE
Feature Request - Copying Sprites from one sheet to another

### ISSUE THREAD

**Issue by Andy1966uk** [remy/zx-tools#19]
Feature of being able to load two sprite sheets and copy sprites from one to another.
i.e. I have one sheet with a sprite that took ages, and I want to copy that to my other sprite sheets... thanks in advance...

**Comment by remy** [comment]
So, this partially works. You can drop a .spr file onto the PNG import and it will _try_ to read the file, but the maths really started to [blow my brain](https://github.com/remy/zx-tools/blob/cfef6ce46a3c5a033951c850216771b2901b32f7/public/sprites/lib/parser.js#L51-L61):

```
ptr = (((i % 16) + 256 * ((i / 16) | 0)) % 4096) + 16 * ((i / 256) | 0)
```

I've managed to use it myself to copy the first 16 sprites from an older sprite sheet, but the maths goes bad after the next row.

I'll certainly get this in, because I've needed it too.

**Comment by Andy1966uk** [comment]
It’s all about maths :) appreciate the work Remy

**Comment by remy** [comment]
I gave up on the maths and went for the simple solution (not realising it was there all along). You can now import 16x and 8x sprite sheets. They'll be rendered in a single column (so 16x1024 for a 16x sprite sheet) which looks a bit naff, but works.

I've also added support for copy over (rather than replace the target sprite) as well as pasting _over_ (hold shift when pasting).

I realise this is way way after you wanted it, but I needed it (again) today so had a crack this evening and managed to solve it (it should be live shortly).
