### ISSUE TITLE
Tile preview 8x8 in map editor is wrong

### ISSUE THREAD

**Issue by Duefectu** [remy/zx-tools#20]
In the sprite and map editor, when editing 8x8 tiles, the tile preview at the left, show the tiles in wrong way. I think as 16x16 tiles as show in this image.
![image](https://user-images.githubusercontent.com/5257547/82764440-f8da2c80-9e0e-11ea-90aa-d78ef869c207.png)

Great work!

**Comment by remy** [comment]
That's correct. The full sprite sheet view shows how the pixels are stored - so in 16x16 arrangements, so you'll see when a sprite has been split into 8x8 with that kind of mess of pixels (which is why there's a sub sheet above which lets you select and preview in a sane way).

That's to say: it's by design.

**Comment by Duefectu** [comment]
I understand the internal design way "as stored in memory", but it's very anyoning when working with tilemap.
![image](https://user-images.githubusercontent.com/5257547/82945569-7469e400-9f9d-11ea-82c1-fb3761f23d3e.png)
No way to work!

**Comment by remy** [comment]
I can see your frustration (and amazing art btw).

I wonder (to myself) if it's so bad that the sprite previews are rearranged in a "fake" way so they make a boat load of visual sense to you as the author…

I just need to reconcile the change in my head because there's a weird back and forth (from 8px to 16px) between the tilemap and the sprite editor...

(By the way, if you click on the triangle next to "Map Settings" it'll collapse the settings and give you more working area).

Give me a bit to look at the code and what's required - I'm not sure if it would  be a big change or small.

**Comment by remy** [comment]
Release going live now that renders the full sprite sheet in an 8x8 layout if you've got the 8x8 sprite button toggled.

**Comment by Duefectu** [comment]
Cool!!!
Thanks for your work!
