### ISSUE TITLE
Load unheaded tile maps fails

### ISSUE THREAD

**Issue by Duefectu** [remy/zx-tools#22]
Last days you added an option to save .map files without header.
It works good, but when update a .map file without headerm the system hangs.

The work arround is to save the work files with header, and save only the "release" versions without header.

By the way, I love your tool and I'm using to develop a new game.
I love the online concept!
Thanks for your work!

**Comment by remy** [comment]
Good catch, I spotted that when I was making the change - because I sneak the map dimensions into the +3dos header so it's easy to reimport, but without the header it doesn't know what dimensions it has.

Obviously it shouldn't blow up like that - I'll fix the import without header, and prompt for the dimensions.

**Comment by remy** [comment]
Bit late to reply to this, but now when you drop/upload a headerless .map file onto the tool, it'll prompt for the width (in tiles) and then it'll render it properly 👍
