### ISSUE TITLE
8px tilemaps default tile index

### ISSUE THREAD

**Issue by celeritydesign** [remy/zx-tools#29]
The default transparent tile when choosing an 8px tilemap is index 63 - to be consistent with 16px tilemaps it should be the last tile, index 255, shouldn't it?

Maybe not a bug, but thought I would check.

**Comment by remy** [comment]
I know what you mean, but it's hardcoded, but more importantly it doesn't switch to 255 because you might already have some pixels in sprite position 63 (in the 8x8 configuration).

It might possibly make more sense to set it to zero, but moreover I think some way to search and replace index values on tile maps is the best solution.
