### ISSUE TITLE
another 'capture' of a few points, sorry

### ISSUE THREAD

**Issue by robsoft** [remy/zx-tools#8]
Sorry Remy not sure if you'd prefer them itemised & detailed, happy to come back and expand this if so.

1) Could we set dimensions of the tile map editor? I guess that means the map display area might need to be a scrollable window etc.

2) I've had some trouble loading a tile map file back in, I can drag it onto the tab but I get something weird back out (is it reading the header as tile data?) Not sure if I'm doing something wrong but happy to make a video or send you tilemap files etc. The maps I'm saving are working great on the machine so I think it's the process of loading back in I'm having trouble with.

3) I've done this now but might be handy to either give you my sprite sheet, or have an option to just generate a 'numbered' set of sprites. So as well as a blank set, you can have a set of numbered tiles (ie, the image on the tile is a number) that can be used and edited as things develop, especially if you're working in a team. I do appreciate that this is niche and once you've made a set, you've always got it handy anyway. :-)

The other stuff I was thinking about thus far, you seem to have already done or got in your previous issue capture. :-)

**Comment by remy** [comment]
1. I wanted to check the bank size, but IIRC it's 64K, that should be the upper range of the tile. I've got some panning logic already in place, so it should be feasible to make that scroll around (otherwise I just use the browser's native scrolling which might be at least a good stopgap). I can't see tile dimension being a problem (famous last words).

2. The .map file has a +3dos header on it, but it should also jump over it when loading in the browser. Can you share the tilemap you've got or perhaps a screenshot of what you're seeing. I wonder if a direct upload botton would help here too.

3. Heh, yeah that's fairly niche, but I can see something like that being useful for prototyping. It might be easier just to make a couple of sprite sheets with numbers and one with letters and have them as some kind of "pre-populate" option (I'd be inclinded to grab something off itch.io, drop into the png importer and populate the spritesheet for re-use in the app).

Don't appologise for suggestions - I made this tool to help my own and other's dev - so these improvements make it better for _me_ too 👍

**Comment by robsoft** [comment]
point 2 - ok, brilliant. Hope this helps - I suspect you're going to have to find a nice way to tell me I'm being an idiot.

Here's my sprite file, the 2 map files, what they looked like in the browser, what they looked like in CSpect (all good so far), then 3 PNGs showing what happened when I try to load them back into the browser. Hope this makes sense!


(argh - needed to zip the map and spr file)
[spr-and-maps.zip](https://github.com/remy/zx-tools/files/4515820/spr-and-maps.zip)
![map 2 in CSpect](https://user-images.githubusercontent.com/4416088/79977335-05790700-8496-11ea-8eb1-7869501403c6.png)
![map 1 in CSpect](https://user-images.githubusercontent.com/4416088/79977341-0742ca80-8496-11ea-870f-0c51ee5a3de9.png)
![map 2 in browser](https://user-images.githubusercontent.com/4416088/79977345-07db6100-8496-11ea-87d9-0ec17b64bfbd.png)
![map 1 in browser](https://user-images.githubusercontent.com/4416088/79977347-0873f780-8496-11ea-9c4f-0e8bb7218652.png)
![1-first reload sprites](https://user-images.githubusercontent.com/4416088/79977357-0f9b0580-8496-11ea-97d0-8fe14e6bac4f.png)
![2-dragged roadmap1 to tile map tab](https://user-images.githubusercontent.com/4416088/79977367-1295f600-8496-11ea-922e-56ac4a655809.png)
![3-sprite editor after dragging roadmap1 to tile map tab](https://user-images.githubusercontent.com/4416088/79977374-145fb980-8496-11ea-9c19-07e9cf26fb34.png)

**Comment by remy** [comment]
Okay, I know what's happening in the tile map upload. 

The drag and drop _anywhere_ is for sprite sheets - to upload a map, you need to open the tile panel and drop it directly on the tilemap canvas (I know, not obvious at all!) - that should hopefully unlock you a little.

That sprite sheet with numbers, would you be happy for it to be used as a sample sprite sheet in the tool?

**Comment by robsoft** [comment]
Ha ha! I *knew* it would be me, what an idiot. Sorry Remy, I hope I haven't wasted much of your time. Yes, that works a treat now, just tried it. Thank you!

Sprite sheet - yes, by all means, it was just a 5 minute scribble to help me visualise stuff when it got over into the Next really, you may do whatever you see fit with it!

**Comment by remy** [comment]
I believe all these issues are now addressed - thanks again for the feedback.

<img width="1074" alt="Screenshot 2020-04-23 at 15 18 01" src="https://user-images.githubusercontent.com/13700/80109639-a12d7480-8575-11ea-8c51-062932486c01.png">

- [x] Resize tilemap
- [x] UI upload button
- [x] Populate spritesheet with test sheet (thank you)
